### ISSUE TITLE
Kylo Job failed ingesting data "ex_quartieri_torino"

### ISSUE THREAD

**Issue by mariaclaudia** [italia/daf-kylo#34]
### Subject of the issue
Kylo feed is created successfully, but job failed when dataset attached is submitted.

### Steps to reproduce
Upload the geojson file attached to .../SOCI/societa/elenco_ex_quartieri_torino
Check job status.

### Expected behaviour
The dataset should be ingested correctly and processed.
[ex_quartieri.geojson.zip](https://github.com/italia/daf-kylo/files/1920075/ex_quartieri.geojson.zip)
 
### Actual behaviour
Job failed. It's not possible to ingest the dataset "ex quartieri"
I've investigated with @panelladavide but we are not able to understand the problem.
The geojson file seems well structured and it's possible to process it using Python,
Please see the python code

 attached.

### Kylo Details
comune_torino_csi_o_elenco_ex_quartieri_torino

System Name
comune_torino_csi_o_elenco_ex_quartieri_torino

Description
elenco_ex_quartieri_torino

Feed Type
Dataset Ingest

Flow Processing
Batch

Kylo will track individual jobs and steps.
Feed Details

Source
Filesystem

Input Directory
/home/comune_torino_csi_daf/SOCI/societa/elenco_ex_quartieri_torino

File Filter
.*json
Table Schema & Data Policies

Source Feed Record Format
ROW FORMAT SERDE 'org.apache.hive.hcatalog.data.JsonSerDe' STORED AS INPUTFORMAT 'org.apache.hadoop.mapred.TextInputFormat' OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.IgnoreKeyTextOutputFormat'
Destination Table Name
comune_torino_csi.comune_torino_csi_o_elenco_ex_quartieri_torino

**Comment by panelladavide** [comment]
The geojson is malformed for hive-impala table insertion, infact "coordinates" key has two different structures, one has three arrays, the other four arrays. This leads to a job spark failure when inserting data into hive-impala table.
**Solution:**
the geojson file must have one fix structure for the whole file
