### ISSUE TITLE
missing kylo database in mysql container

### ISSUE THREAD

**Issue by keven4ever** [italia/daf-kylo#37]
*Note: These issues are for bugs and feature requests.*

### Subject of the issue
missing kylo database in mysql container

### Your environment
docker for mac with k8s

### Steps to reproduce
Since i installed everything on mac, so i remove most of persistent volume in deployment yaml and when start kylo-services container, it complains kylo database is not available.

### Expected behaviour
I expected some sql script in mysql Dockerfile to create kylo database and so on.

**Comment by panelladavide** [comment]
Duplicate of #33
